---
- hosts: all
  become: false
  tasks:

  - name: Update cache in debian
    apt:
      update_cache: yes

  - name: upgrade packages in debian
    become_user: root
    apt:
      upgrade: full
      state: latest
      allow_downgrade: yes

  - name: clean packages in debian
    apt:
      autoclean: yes
      autoremove: yes