---
- hosts: all
  become: true
  tasks:

  - name: Update in ubuntu
    apt:
      update_cache: yes

  - name: upgrade in ubuntu
    become_user: root
    apt:
      upgrade: full
      state: latest
      allow_downgrade: yes

  - name: clean in ubuntu
    apt:
      autoclean: yes
      autoremove: yes